# Generated by Django 3.2.8 on 2022-01-08 04:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import site_info.uploaders
import site_info.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='سایت حسین', max_length=50, null=True, verbose_name='اسم سایت')),
                ('logo', models.ImageField(blank=True, default='defaults/logo.png', null=True, upload_to=site_info.uploaders.site_logo_uploader, verbose_name='لوگوی سایت')),
                ('phone', models.CharField(blank=True, default='021-22712443', max_length=12, null=True, validators=[site_info.validators.validate_static_phone_number], verbose_name='شماره تلفن ثابت سایت')),
                ('email', models.EmailField(blank=True, default='hosseintaheri76@gmail.com', max_length=254, null=True, verbose_name='ایمیل سایت')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='آدرس شرکت')),
                ('short_about', models.TextField(blank=True, max_length=100, null=True, verbose_name='درباره ی ما مختصر')),
                ('copyright', models.TextField(blank=True, max_length=100, null=True, verbose_name='کپی رایت فوتر')),
                ('full_about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوی صفحه درباره ی ما')),
                ('rules_page', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='محتوی صفحه قوانین سایت')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رسانه اجتماعی')),
                ('link', models.URLField(verbose_name='لینک')),
                ('css_icon_class', models.CharField(max_length=50, verbose_name='کلاس css آیکون مربوطه')),
                ('site_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='site_info.siteinfo')),
            ],
        ),
    ]
