# Generated by Django 3.2.8 on 2022-01-08 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fullname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی ارسال کننده')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('text', models.TextField(max_length=300, verbose_name='متن پیام')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='مربوط به محصول')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_fullname', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی ارسال کننده')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('text', models.TextField(max_length=300, verbose_name='متن پیام')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='مریط به مقاله')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
