# Generated by Django 3.2.8 on 2022-01-08 04:04

import ckeditor.fields
import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('phone', models.CharField(max_length=14, validators=[contact.validators.validate_phone], verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('question_text', models.TextField(verbose_name='متن پیام')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیام')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده/نشده')),
                ('answer_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پاسخ مدیر')),
            ],
            options={
                'verbose_name': 'پیام کاربر',
                'verbose_name_plural': 'پیام کاربران',
            },
        ),
    ]
