# Generated by Django 3.2.8 on 2022-01-08 04:04

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(blank=True, null=True, unique=True, verbose_name='شماره سفارش')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ثبت سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/ نشده')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='وضعیت سفارش')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس ارسال')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, validators=[accounts.validators.validate_phone], verbose_name='شماره تماس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='تعداد محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
